# Generated by Django 5.2.10 on 2026-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chapter_number", models.IntegerField(verbose_name="회차 번호")),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                ("content", models.TextField(verbose_name="마크다운 내용")),
                ("content_html", models.TextField(blank=True, verbose_name="HTML 내용")),
                ("word_count", models.IntegerField(default=0, verbose_name="글자 수")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "임시저장"),
                            ("SCHEDULED", "예약"),
                            ("PUBLISHED", "발행됨"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("FREE", "무료"), ("SUBSCRIPTION", "구독")],
                        default="FREE",
                        max_length=20,
                        verbose_name="접근 타입",
                    ),
                ),
                ("price", models.IntegerField(default=0, verbose_name="가격")),
                (
                    "scheduled_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="예약 시간"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="발행 시간"),
                ),
                ("view_count", models.BigIntegerField(default=0, verbose_name="조회수")),
                ("like_count", models.BigIntegerField(default=0, verbose_name="좋아요 수")),
                ("comment_count", models.IntegerField(default=0, verbose_name="댓글 수")),
            ],
            options={
                "verbose_name": "회차",
                "verbose_name_plural": "회차들",
                "db_table": "chapters",
                "ordering": ["chapter_number"],
            },
        ),
    ]
