# Generated by Django 5.2.10 on 2026-01-13 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contents", "0001_initial"),
        ("novels", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="novels.branch",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("branch", "chapter_number")},
        ),
    ]
