# Generated by Django 5.2.10 on 2026-01-13 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_initial'),
        ('novels', '0003_add_linked_branch_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiTagDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='태그명')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='색상')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='아이콘')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('display_order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_tag_definitions', to='novels.branch')),
            ],
            options={
                'verbose_name': '위키 태그 정의',
                'verbose_name_plural': '위키 태그 정의들',
                'db_table': 'wiki_tag_definitions',
                'ordering': ['display_order', 'name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WikiEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('image_url', models.URLField(blank=True, verbose_name='이미지 URL')),
                ('first_appearance', models.IntegerField(blank=True, null=True, verbose_name='첫 등장 회차')),
                ('hidden_note', models.TextField(blank=True, verbose_name='작가 노트 (비공개)')),
                ('ai_metadata', models.JSONField(blank=True, null=True, verbose_name='AI 메타데이터')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_entries', to='novels.branch')),
                ('source_wiki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forked_wikis', to='contents.wikientry')),
                ('tags', models.ManyToManyField(blank=True, db_table='wiki_tags', related_name='wiki_entries', to='contents.wikitagdefinition')),
            ],
            options={
                'verbose_name': '위키 엔트리',
                'verbose_name_plural': '위키 엔트리들',
                'db_table': 'wiki_entries',
                'ordering': ['name'],
                'unique_together': {('branch', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WikiSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='내용')),
                ('valid_from_chapter', models.IntegerField(verbose_name='유효 시작 회차')),
                ('contributor_type', models.CharField(choices=[('USER', '사용자'), ('AI', 'AI')], default='USER', max_length=10, verbose_name='기여자 유형')),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wiki_contributions', to=settings.AUTH_USER_MODEL)),
                ('wiki_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='contents.wikientry')),
            ],
            options={
                'verbose_name': '위키 스냅샷',
                'verbose_name_plural': '위키 스냅샷들',
                'db_table': 'wiki_snapshots',
                'ordering': ['valid_from_chapter'],
                'unique_together': {('wiki_entry', 'valid_from_chapter')},
            },
        ),
    ]
