# Generated by Django 5.2.10 on 2026-01-13 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0003_wiki_models"),
        ("novels", "0003_add_linked_branch_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("BASE", "기본 레이어"),
                            ("OVERLAY", "오버레이"),
                            ("MARKER", "마커"),
                            ("PATH", "경로"),
                            ("REGION", "지역"),
                        ],
                        default="OVERLAY",
                        max_length=50,
                        verbose_name="레이어 타입",
                    ),
                ),
                ("z_index", models.IntegerField(default=0, verbose_name="Z 순서")),
                ("is_visible", models.BooleanField(default=True, verbose_name="표시 여부")),
                ("style_json", models.JSONField(blank=True, null=True, verbose_name="스타일 JSON")),
            ],
            options={
                "verbose_name": "지도 레이어",
                "verbose_name_plural": "지도 레이어들",
                "db_table": "map_layers",
                "ordering": ["z_index", "name"],
            },
        ),
        migrations.CreateModel(
            name="Map",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("width", models.IntegerField(verbose_name="가로 크기")),
                ("height", models.IntegerField(verbose_name="세로 크기")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maps",
                        to="novels.branch",
                    ),
                ),
                (
                    "source_map",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forked_maps",
                        to="contents.map",
                    ),
                ),
            ],
            options={
                "verbose_name": "지도",
                "verbose_name_plural": "지도들",
                "db_table": "maps",
                "ordering": ["name"],
                "unique_together": {("branch", "name")},
            },
        ),
        migrations.CreateModel(
            name="MapObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("POINT", "포인트"),
                            ("LINE", "선"),
                            ("POLYGON", "다각형"),
                            ("CIRCLE", "원"),
                            ("ICON", "아이콘"),
                        ],
                        default="POINT",
                        max_length=50,
                        verbose_name="오브젝트 타입",
                    ),
                ),
                ("coordinates", models.JSONField(verbose_name="좌표")),
                ("label", models.CharField(blank=True, max_length=100, verbose_name="라벨")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("style_json", models.JSONField(blank=True, null=True, verbose_name="스타일 JSON")),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objects",
                        to="contents.maplayer",
                    ),
                ),
                (
                    "wiki_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="map_objects",
                        to="contents.wikientry",
                    ),
                ),
            ],
            options={
                "verbose_name": "지도 오브젝트",
                "verbose_name_plural": "지도 오브젝트들",
                "db_table": "map_objects",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="MapSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("valid_from_chapter", models.IntegerField(verbose_name="유효 시작 회차")),
                (
                    "base_image_url",
                    models.URLField(blank=True, max_length=500, verbose_name="기본 이미지 URL"),
                ),
                (
                    "map",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="contents.map",
                    ),
                ),
            ],
            options={
                "verbose_name": "지도 스냅샷",
                "verbose_name_plural": "지도 스냅샷들",
                "db_table": "map_snapshots",
                "ordering": ["valid_from_chapter"],
                "unique_together": {("map", "valid_from_chapter")},
            },
        ),
        migrations.AddField(
            model_name="maplayer",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="layers",
                to="contents.mapsnapshot",
            ),
        ),
    ]
