# Generated by Django 5.2.10 on 2026-01-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_add_map_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapobject',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_objects', to='contents.maplayer'),
        ),
    ]
