# Generated by Django 5.2.10 on 2026-01-13 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_wiki_models'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('interactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '좋아요',
                'verbose_name_plural': '좋아요들',
                'db_table': 'likes',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='paragraph_index',
            field=models.IntegerField(blank=True, null=True, verbose_name='문단 인덱스'),
        ),
        migrations.AddField(
            model_name='comment',
            name='quoted_text',
            field=models.TextField(blank=True, verbose_name='인용 텍스트'),
        ),
        migrations.AddField(
            model_name='comment',
            name='selection_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='선택 끝'),
        ),
        migrations.AddField(
            model_name='comment',
            name='selection_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='선택 시작'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['chapter', 'paragraph_index'], name='comments_chapter_9ca3c8_idx'),
        ),
        migrations.AddField(
            model_name='like',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['content_type', 'object_id'], name='likes_content_8cb9c7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
