# Generated by Django 5.2.10 on 2026-01-13 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("interactions", "0003_add_paragraph_comment_and_like"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "스팸"),
                            ("ABUSE", "욕설/비방"),
                            ("SPOILER", "스포일러"),
                            ("COPYRIGHT", "저작권 침해"),
                            ("OTHER", "기타"),
                        ],
                        max_length=20,
                        verbose_name="신고 사유",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="상세 설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("RESOLVED", "처리완료"),
                            ("REJECTED", "반려"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True, verbose_name="처리일")),
                ("resolution_note", models.TextField(blank=True, verbose_name="처리 메모")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "신고",
                "verbose_name_plural": "신고들",
                "db_table": "reports",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="reports_content_0cd725_idx"
                    ),
                    models.Index(fields=["status"], name="reports_status_e83c1d_idx"),
                ],
                "unique_together": {("reporter", "content_type", "object_id")},
            },
        ),
    ]
