# Generated by Django 5.2.10 on 2026-01-13 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_add_report_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.IntegerField(default=0, verbose_name='잔액')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '지갑',
                'verbose_name_plural': '지갑들',
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('CHARGE', '충전'), ('SPEND', '사용'), ('REFUND', '환불'), ('ADJUSTMENT', '정정')], max_length=20, verbose_name='거래 유형')),
                ('amount', models.IntegerField(verbose_name='금액')),
                ('balance_after', models.IntegerField(verbose_name='거래 후 잔액')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='참조 타입')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='참조 ID')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='interactions.wallet')),
            ],
            options={
                'verbose_name': '코인 거래',
                'verbose_name_plural': '코인 거래들',
                'db_table': 'coin_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='coin_transa_wallet__894c8d_idx'), models.Index(fields=['transaction_type'], name='coin_transa_transac_e75264_idx'), models.Index(fields=['reference_type', 'reference_id'], name='coin_transa_referen_be3f67_idx')],
            },
        ),
    ]
