# Generated by Django 5.2.10 on 2026-01-13 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interactions", "0005_add_wallet_and_transactions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("usage_date", models.DateField(verbose_name="사용일")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("WIKI_SUGGEST", "위키 제안"),
                            ("CONSISTENCY_CHECK", "일관성 검사"),
                            ("ASK", "질문"),
                        ],
                        max_length=30,
                        verbose_name="액션 타입",
                    ),
                ),
                ("request_count", models.IntegerField(default=0, verbose_name="요청 횟수")),
                ("token_count", models.IntegerField(default=0, verbose_name="토큰 수")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 사용 로그",
                "verbose_name_plural": "AI 사용 로그들",
                "db_table": "ai_usage_logs",
                "indexes": [
                    models.Index(
                        fields=["usage_date", "user"], name="ai_usage_lo_usage_d_33e064_idx"
                    ),
                    models.Index(
                        fields=["user", "action_type", "usage_date"],
                        name="ai_usage_lo_user_id_0899ce_idx",
                    ),
                ],
                "unique_together": {("user", "usage_date", "action_type")},
            },
        ),
    ]
