# Generated by Django 5.2.10 on 2026-01-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False, verbose_name='메인 브랜치')),
                ('fork_point_chapter', models.IntegerField(blank=True, null=True, verbose_name='분기 회차')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='표지')),
                ('branch_type', models.CharField(choices=[('MAIN', '메인'), ('SIDE_STORY', '외전'), ('FAN_FIC', '팬픽'), ('IF_STORY', 'IF 스토리')], default='FAN_FIC', max_length=20, verbose_name='브랜치 타입')),
                ('visibility', models.CharField(choices=[('PRIVATE', '비공개'), ('PUBLIC', '공개'), ('LINKED', '연결됨')], default='PRIVATE', max_length=20, verbose_name='공개 상태')),
                ('canon_status', models.CharField(choices=[('NON_CANON', '비정사'), ('CANDIDATE', '후보'), ('MERGED', '편입됨')], default='NON_CANON', max_length=20, verbose_name='정사 상태')),
                ('merged_at_chapter', models.IntegerField(blank=True, null=True, verbose_name='편입 회차')),
                ('vote_count', models.BigIntegerField(default=0, verbose_name='투표 수')),
                ('vote_threshold', models.IntegerField(default=1000, verbose_name='투표 임계값')),
                ('view_count', models.BigIntegerField(default=0, verbose_name='조회수')),
                ('chapter_count', models.IntegerField(default=0, verbose_name='회차 수')),
            ],
            options={
                'verbose_name': '브랜치',
                'verbose_name_plural': '브랜치들',
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='BranchLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('APPROVED', '승인됨'), ('REJECTED', '거절됨')], default='PENDING', max_length=20, verbose_name='상태')),
                ('request_message', models.TextField(blank=True, verbose_name='요청 메시지')),
                ('review_comment', models.TextField(blank=True, verbose_name='리뷰 코멘트')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='리뷰 일시')),
            ],
            options={
                'verbose_name': '브랜치 연결 요청',
                'verbose_name_plural': '브랜치 연결 요청들',
                'db_table': 'branch_link_requests',
            },
        ),
        migrations.CreateModel(
            name='BranchVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'branch_votes',
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('cover_image_url', models.URLField(blank=True, verbose_name='표지')),
                ('genre', models.CharField(choices=[('FANTASY', '판타지'), ('ROMANCE', '로맨스'), ('ACTION', '액션'), ('THRILLER', '스릴러'), ('MYSTERY', '미스터리'), ('SF', 'SF'), ('HISTORY', '대체역사'), ('MODERN', '현대'), ('MARTIAL', '무협'), ('GAME', '게임')], max_length=50, verbose_name='장르')),
                ('age_rating', models.CharField(choices=[('ALL', '전체'), ('12', '12세'), ('15', '15세'), ('19', '19세')], default='ALL', max_length=10, verbose_name='연령등급')),
                ('status', models.CharField(choices=[('ONGOING', '연재중'), ('COMPLETED', '완결'), ('HIATUS', '휴재')], default='ONGOING', max_length=20, verbose_name='상태')),
                ('allow_branching', models.BooleanField(default=True, verbose_name='브랜치 허용')),
                ('total_view_count', models.BigIntegerField(default=0, verbose_name='총 조회수')),
                ('total_like_count', models.BigIntegerField(default=0, verbose_name='총 좋아요')),
                ('total_chapter_count', models.IntegerField(default=0, verbose_name='총 회차 수')),
                ('branch_count', models.IntegerField(default=1, verbose_name='브랜치 수')),
            ],
            options={
                'verbose_name': '소설',
                'verbose_name_plural': '소설들',
                'db_table': 'novels',
                'ordering': ['-created_at'],
            },
        ),
    ]
