# Generated by Django 5.2.10 on 2026-01-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("novels", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="novel",
            name="linked_branch_count",
            field=models.IntegerField(default=0, verbose_name="연결된 브랜치 수"),
        ),
    ]
