# Generated by Django 5.2.10 on 2026-01-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_add_linked_branch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='is_exclusive',
            field=models.BooleanField(default=False, verbose_name='독점작'),
        ),
        migrations.AddField(
            model_name='novel',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='프리미엄'),
        ),
    ]
