# Generated by Django 5.2.10 on 2026-01-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_novel_is_exclusive_novel_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='version',
            field=models.IntegerField(default=0, verbose_name='버전'),
        ),
    ]
